spring:
  
  application:
    name: log-service
  
  cloud:
    # ======================nacos==================
    nacos:
      discovery:
        # Nacos服务注册中心地址 host+端口
        server-addr: yourNacosAddress
        # 注册进nacos的，用来让网关访问此实例的ip，根据实际情况修改
        ip: 127.0.0.1
        # 注册进nacos的，用来让网关访问此实例的port，根据实际情况修改
        port: 3000
  
  # ======================rabbit mq==================
  rabbitmq:
    host: yourRabbitMqHost
    port: yourRabbitMqPort
    username: yourRabbitMqUserName
    password: yourRabbitMqPassword
  
  data:
    # ======================mongodb==================
    mongodb:
      host: yourMongodbHost
      port: yourMongodbPort
      database: yourTableName
      username: yourUserName
      password: yourPassword
      # 储存用户信息的库
      authentication-database: yourAuthenticationDatabase
    
    # ======================redis==================
    redis:
      host: yourRedisHost
      password: yourRedisPassword
      database: 0
      port: yourRedisPasswordPort
      # 这边是用作登录校验的key
      LOGIN_KEY: yourLoginKey

server:
  port: 3000
